In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [3]:
account = pd.read_csv('../data/account.csv', sep=';')
account.head()

   account_id  district_id         frequency    date
0         576           55  POPLATEK MESICNE  930101
1        3818           74  POPLATEK MESICNE  930101
2         704           55  POPLATEK MESICNE  930101
3        2378           16  POPLATEK MESICNE  930101
4        2632           24  POPLATEK MESICNE  930102

In [4]:
account['date_parsed'] = pd.to_datetime(account['date'], format='%y%m%d')
account.head()

   account_id  district_id         frequency    date date_parsed
0         576           55  POPLATEK MESICNE  930101  1993-01-01
1        3818           74  POPLATEK MESICNE  930101  1993-01-01
2         704           55  POPLATEK MESICNE  930101  1993-01-01
3        2378           16  POPLATEK MESICNE  930101  1993-01-01
4        2632           24  POPLATEK MESICNE  930102  1993-01-02

# Berka dates are 1993-1999, safely within pandas' default 1969-1999 pivot for 2-digit years.
# Verified: no dates fall outside this range.

In [5]:
account['date_parsed'].dt.year.describe()

count    4500.000000
mean     1995.098222
std         1.483898
min      1993.000000
25%      1993.000000
50%      1996.000000
75%      1996.000000
max      1997.000000
Name: date_parsed, dtype: float64